version: '3'
services:
  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bankcards
      - POSTGRES_PASSWORD=12345
    volumes:
      - "db-data:/var/lib/postgresql/data"


  app:
    build:
      context: app
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/bankcards
      - JS_URL=http://localhost
    image: 'my-bankcard-application'
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  db-data: